#this dockerfile exists for semantics and if I want to add a redis.conf in the future
#my redis server is just to queue requests.
FROM redis
#COPY redis.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server"]